# Actuator Selection
Single model analysis - V1

##### Py Packages

In [1]:
import numpy as np
from copy import deepcopy as dc

from functionfile_system_definition import sys_from_file, system_display_matrix, matrix_splitter
from functionfile_system_mplcost import cost_function_1, initial_values_init, actuator_selection_cost_1, plot_actuator_selection_1, estimation_actuator_selection, plot_actuator_selection_2, simulation_actuator_selection, plot_simulation

## Code

In [2]:
sys_model = 'System Model 3'
S = sys_from_file(sys_model)

System read from file @ system_model/System Model 3.pickle 



In [3]:
print(S['A'])
matrix_splitter(S['A'])

[[0.35689587 0.35689587 0.         0.         0.         0.        ]
 [0.35689587 0.35689587 0.35689587 0.         0.         0.        ]
 [0.         0.35689587 0.35689587 0.35689587 0.         0.        ]
 [0.         0.         0.35689587 0.35689587 0.35689587 0.        ]
 [0.         0.         0.         0.35689587 0.35689587 0.35689587]
 [0.         0.         0.         0.         0.35689587 0.35689587]]
(17, 6, 6)
(16, 6, 6)


array([[[1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
      

In [4]:
# ret1 = cost_function_1(S)

# ret2 = actuator_selection_cost_1(S)
# system_display_matrix(ret2['system'])

# ret3 = estimation_actuator_selection(ret2['system'])
# # print(ret3)
# plot_actuator_selection_2(ret3)

# ret4 = simulation_actuator_selection(ret2['system'], ret2['system'])
# plot_simulation(ret4)