# Actuator Selection - Comparison based on state-mpl differences
Model A vs B testing

##### Py Packages

In [1]:
import warnings
import numpy as np
from copy import deepcopy as dc
%matplotlib widget

from functionfile_system_definition import sys_from_file, system_display_matrix
from functionfile_system_mplcost import initial_values_init, actuator_selection_cost_1, estimation_actuator_selection, plot_actuator_selection_2, plot_actuator_selection_comparison_1

## Code

In [2]:
sys_model = 'System Model 5' # Comparing A and B

***
### Model A

##### Code

In [3]:
S_A = sys_from_file(sys_model+'A')
initial_values = initial_values_init(S_A)

System read from file @ system_model/System Model 5A.pickle 



In [4]:
ret1_A = actuator_selection_cost_1(S_A)
S1_A = ret1_A['system']
ret2_A = estimation_actuator_selection(S1_A, initial_values=initial_values)

##### Output

In [5]:
system_display_matrix(S1_A)
plot_actuator_selection_2(ret2_A)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

***
### Model B

##### Code

In [6]:
S_B = sys_from_file(sys_model+'B')
initial_values = initial_values_init(S_B)

System read from file @ system_model/System Model 5B.pickle 



In [7]:
ret1_B = actuator_selection_cost_1(S_B)
S1_B = ret1_B['system']
ret2_B = estimation_actuator_selection(S1_B, initial_values=initial_values)

##### Output

In [8]:
system_display_matrix(S1_B)
plot_actuator_selection_2(ret2_B)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

***
## Cost and Actuator Selection comparison

##### Costs

In [9]:
print(sys_model+'A')
with warnings.catch_warnings():
    warnings.simplefilter(action='ignore', category=FutureWarning)
    for key in ret2_A:
        if 'cost' in ret2_A[key]:
            print('|S|:', key, ' | cost:', ret2_A[key]['cost'], ' | time:', ret2_A[key]['time'], ' | check:', ret2_A[key]['check'])

System Model 5A
|S|: 0  | cost: 5112790221.3527355  | time: 60  | check: 3
|S|: 1  | cost: 555.5788384150108  | time: 136  | check: 0
|S|: 2  | cost: 168.53730550266002  | time: 69  | check: 0
|S|: 3  | cost: 145.90138480706204  | time: 67  | check: 0
|S|: 4  | cost: 129.20286821041134  | time: 64  | check: 0
|S|: 5  | cost: 119.93212982091696  | time: 64  | check: 0
|S|: 6  | cost: 118.39009193010018  | time: 61  | check: 0
|S|: 7  | cost: 116.66017446826153  | time: 60  | check: 0
|S|: 8  | cost: 116.29587855319791  | time: 60  | check: 0


In [10]:
print(sys_model+'B')
with warnings.catch_warnings():
    warnings.simplefilter(action='ignore', category=FutureWarning)
    for key in ret2_B:
        if 'cost' in ret2_B[key]:
            print('|S|:', key, ' | cost:', ret2_B[key]['cost'], ' | time:', ret2_B[key]['time'], ' | check:', ret2_B[key]['check'])

System Model 5B
|S|: 0  | cost: 128.65501196612576  | time: 49  | check: 0
|S|: 1  | cost: 95.68768435562724  | time: 39  | check: 0
|S|: 2  | cost: 86.89991441210915  | time: 26  | check: 0
|S|: 3  | cost: 79.01019332200723  | time: 23  | check: 0
|S|: 4  | cost: 74.29211570540363  | time: 19  | check: 0
|S|: 5  | cost: 72.09348569967294  | time: 17  | check: 0
|S|: 6  | cost: 71.03140193971419  | time: 14  | check: 0
|S|: 7  | cost: 70.44258597583075  | time: 14  | check: 0
|S|: 8  | cost: 69.86249925447827  | time: 12  | check: 0


##### Actuator Selection

In [11]:
if np.allclose(ret2_A['B'], ret2_B['B']):
    print('Both actuator sets are close/equal')
else:
    print('Actuator sets are different')

Actuator sets are different


In [12]:
print(sys_model+'A')
print(ret2_A['B'])

System Model 5A
[[0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [13]:
print(sys_model+'B')
print(ret2_B['B'])

System Model 5B
[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


##### Comparison Plot

In [14]:
plot_actuator_selection_comparison_1(ret2_A, ret2_B)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …