# Comparison of control gain 'K' and cost matrix 'P' for different state-mpl for same actuator set 'B'

In [1]:
import numpy as np
from copy import deepcopy as dc

from functionfile_system_definition import sys_from_file, system_display_matrix
from functionfile_system_mplcost import cost_function_1, initial_values_init, actuator_selection_cost_1, plot_actuator_selection_1, simulation_actuator_selection, plot_simulation

In [2]:
sys_model = 'System Model 1' # Comparing A and B

### Model A

##### Code

In [3]:
S_A = sys_from_file(sys_model+'A')
initial_values = initial_values_init(S_A)

System read from file @ system_model/System Model 1A.pickle 



In [4]:
ret1_A = cost_function_1(S_A, initial_values)

##### Output

In [5]:
print('\n P_mat:\n', ret1_A['P_mat'])
print('\n Gain K:\n', ret1_A['K'])


 P_mat:
 [[1.1118763  0.10754476 0.06141443 0.01110565 0.0048541  0.00360018
  0.01565295 0.02715497]
 [0.10754476 1.16100952 0.11738111 0.06502529 0.01192731 0.0051066
  0.00367546 0.01565295]
 [0.06141443 0.11738111 1.16426544 0.11816916 0.06526847 0.01198543
  0.0051066  0.00360018]
 [0.01110565 0.06502529 0.11816916 1.16449252 0.11822423 0.06526847
  0.01192731 0.0048541 ]
 [0.0048541  0.01192731 0.06526847 0.11822423 1.16449252 0.11816916
  0.06502529 0.01110565]
 [0.00360018 0.0051066  0.01198543 0.06526847 0.11816916 1.16426544
  0.11738111 0.06141443]
 [0.01565295 0.00367546 0.0051066  0.01192731 0.06502529 0.11738111
  1.16100952 0.10754476]
 [0.02715497 0.01565295 0.00360018 0.0048541  0.01110565 0.06141443
  0.10754476 1.1118763 ]]

 Gain K:
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


### Model B

##### Code

In [6]:
S_B = sys_from_file(sys_model+'B')
initial_values = initial_values_init(S_B)

System read from file @ system_model/System Model 1B.pickle 



In [7]:
ret1_B = cost_function_1(S_B, initial_values)

##### Output

In [8]:
print('\n P_mat:\n', ret1_B['P_mat'])
print('\n Gain K:\n', ret1_B['K'])


 P_mat:
 [[1.15709671 0.14258466 0.07137969 0.01512384 0.00611884 0.00456886
  0.01746313 0.04111717]
 [0.14258466 1.20699613 0.15010747 0.07405881 0.0154629  0.00626201
  0.00509536 0.01890207]
 [0.07137969 0.15010747 1.20175283 0.14464523 0.0722733  0.01470201
  0.00608177 0.00507112]
 [0.01512384 0.07405881 0.14464523 1.19302664 0.13834764 0.07029696
  0.01382825 0.00558033]
 [0.00611884 0.0154629  0.0722733  0.13834764 1.18476283 0.13220876
  0.06822336 0.01220876]
 [0.00456886 0.00626201 0.01470201 0.07029696 0.13220876 1.17704169
  0.1256117  0.06293284]
 [0.01746313 0.00509536 0.00608177 0.01382825 0.06822336 0.1256117
  1.16708509 0.11048604]
 [0.04111717 0.01890207 0.00507112 0.00558033 0.01220876 0.06293284
  0.11048604 1.11317632]]

 Gain K:
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


### Comparison

In [9]:
if np.allclose(ret1_A['P_mat'], ret1_B['P_mat']):
    print('Both cost matrices are close/equal')
else:
    print('Cost matrices are different')

if np.allclose(ret1_A['K'], ret1_B['K']):
    print('Both gains are close/equal')
else:
    print('Gains are different')


Cost matrices are different
Both gains are close/equal
